#!/usr/bin/env python3
"""Make the generated native projects able to receive push.

android/ and ios/ are generated by `cap add`, not committed, so anything they
need beyond Capacitor's defaults is applied here, after generation, by CI and
on a Mac alike:

    python3 tools/native.py --android
    python3 tools/native.py --ios

Android
  google-services.json   the Firebase client config, into android/app. Taken
                         from $GOOGLE_SERVICES_JSON (raw or base64), else from
                         a file beside the repo or inside it. Never committed.
  ic_stat_discern        the status bar icon: the Xurface mark, one colour, as
                         Android requires; without it Android draws a white
                         square
  manifest meta-data     that icon, its tint, and `discern` as the channel a
                         message without one lands on

iOS
  GoogleService-Info.plist   into ios/App/App, and added to the Xcode target
  App.entitlements           aps-environment, which push needs
  Info.plist                 remote-notification background mode
  AppDelegate.swift          hands the APNs token and incoming pushes to the
                             Firebase plugin, which cannot see them otherwise

Running it twice changes nothing the second time.
"""
from __future__ import annotations
import argparse, base64, json, os, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ACCENT = "#3B6EA3"          # --xur, the Xurface matte blue


def secret_file(env: str, name: str) -> bytes | None:
    raw = os.environ.get(env, "").strip()
    if raw:
        if raw.startswith("{") or raw.startswith("<"):
            return raw.encode()
        return base64.b64decode(raw)
    for p in (ROOT / name, ROOT.parent / name):
        if p.exists():
            return p.read_bytes()
    return None


# ----------------------------------------------------------------- android --
# The mark from tools/brand.py, as a vector: the wave, then the ring.
STAT_ICON = """<?xml version="1.0" encoding="utf-8"?>
<!-- generated by tools/native.py: the Xurface mark, one colour, for the status bar -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp" android:height="24dp"
    android:viewportWidth="256" android:viewportHeight="256">
  <group android:translateX="0" android:translateY="0">
    <path android:strokeColor="#FFFFFFFF" android:strokeWidth="22"
        android:strokeLineCap="round" android:strokeLineJoin="round" android:fillColor="#00000000"
        android:pathData="M18,160 C49.9,160 44.1,96 76,96 C107.9,96 102.1,160 134,160 C150,160 156,156 156,128" />
    <path android:strokeColor="#FFFFFFFF" android:strokeWidth="22" android:fillColor="#00000000"
        android:pathData="M224,128 A34,34 0 1,1 156,128 A34,34 0 1,1 224,128 Z" />
  </group>
</vector>
"""

META = {
    "com.google.firebase.messaging.default_notification_icon": ("resource", "@drawable/ic_stat_discern"),
    "com.google.firebase.messaging.default_notification_color": ("resource", "@color/discern_accent"),
    "com.google.firebase.messaging.default_notification_channel_id": ("value", "discern"),
}


def android():
    app = ROOT / "android" / "app"
    if not app.exists():
        sys.exit("android/ is missing: run `npx cap add android` first")
    gs = secret_file("GOOGLE_SERVICES_JSON", "google-services.json")
    if gs:
        pkg = json.loads(gs)["client"][0]["client_info"]["android_client_info"]["package_name"]
        if pkg != "com.xurface.discern.app":
            sys.exit(f"google-services.json is for {pkg}, not com.xurface.discern.app")
        (app / "google-services.json").write_bytes(gs)
        print("  android/app/google-services.json")
    else:
        print("::warning::no google-services.json: the app builds, but phones will not receive push")

    res = app / "src" / "main" / "res"
    (res / "drawable").mkdir(parents=True, exist_ok=True)
    (res / "drawable" / "ic_stat_discern.xml").write_text(STAT_ICON)
    (res / "values" / "discern_push.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n<resources>\n'
        f'    <color name="discern_accent">{ACCENT}</color>\n</resources>\n')
    print("  res/drawable/ic_stat_discern.xml, res/values/discern_push.xml")

    man = app / "src" / "main" / "AndroidManifest.xml"
    s = man.read_text()
    for name, (kind, val) in META.items():
        if name in s:
            continue
        tag = f'\n        <meta-data android:name="{name}" android:{kind}="{val}" />'
        s = s.replace("</application>", tag + "\n    </application>", 1)
    man.write_text(s)
    print("  AndroidManifest.xml: notification icon, colour and default channel")


# --------------------------------------------------------------------- ios --
ENTITLEMENTS = """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>aps-environment</key>
	<string>{env}</string>
</dict>
</plist>
"""


def ios(env: str):
    appdir = ROOT / "ios" / "App" / "App"
    if not appdir.exists():
        sys.exit("ios/ is missing: run `npx cap add ios` first")
    plist = secret_file("GOOGLE_SERVICE_INFO_PLIST", "GoogleService-Info.plist")
    if plist:
        if b"com.xurface.discern.app" not in plist:
            sys.exit("GoogleService-Info.plist is not for com.xurface.discern.app")
        (appdir / "GoogleService-Info.plist").write_bytes(plist)
        print("  ios/App/App/GoogleService-Info.plist")
    else:
        print("::warning::no GoogleService-Info.plist: the app builds, but iPhones will not receive push")
    (appdir / "App.entitlements").write_text(ENTITLEMENTS.format(env=env))
    print(f"  ios/App/App/App.entitlements (aps-environment {env})")

    info = appdir / "Info.plist"
    s = info.read_text()
    if "UIBackgroundModes" not in s:
        s = s.replace("<dict>", "<dict>\n\t<key>UIBackgroundModes</key>\n\t<array>\n\t\t<string>remote-notification</string>\n\t</array>", 1)
        info.write_text(s)
    print("  Info.plist: remote-notification background mode")

    # APNs talks to the app delegate, not to plugins: pass both on
    ad = appdir / "AppDelegate.swift"
    a = ad.read_text()
    if "capacitorDidRegisterForRemoteNotifications" not in a:
        hooks = """
    // push: APNs reports to the app delegate, so the token and incoming
    // messages are handed to the Firebase plugin from here (tools/native.py)
    func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        NotificationCenter.default.post(name: .capacitorDidRegisterForRemoteNotifications, object: deviceToken)
    }

    func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
        NotificationCenter.default.post(name: .capacitorDidFailToRegisterForRemoteNotifications, object: error)
    }

    func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any],
                     fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
        NotificationCenter.default.post(name: Notification.Name.init("didReceiveRemoteNotification"),
                                        object: completionHandler, userInfo: userInfo)
    }
"""
        i = a.rindex("}")
        a = a[:i].rstrip() + "\n" + hooks + "}\n"
        ad.write_text(a)
    print("  AppDelegate.swift: APNs token and pushes handed to the plugin")

    # the project file has to know about both files, or Xcode ignores them
    pbx = ROOT / "ios" / "App" / "App.xcodeproj" / "project.pbxproj"
    p = pbx.read_text()
    if "CODE_SIGN_ENTITLEMENTS" not in p:
        p = re.sub(r"(INFOPLIST_FILE = App/Info.plist;)", r"CODE_SIGN_ENTITLEMENTS = App/App.entitlements;\n\t\t\t\t\1", p)
    if plist and "GoogleService-Info.plist" not in p:
        fid, bid = "D15C0FE0000000000000A001", "D15C0FE0000000000000A002"
        p = p.replace("/* Begin PBXBuildFile section */",
            "/* Begin PBXBuildFile section */\n\t\t" + bid +
            " /* GoogleService-Info.plist in Resources */ = {isa = PBXBuildFile; fileRef = " + fid +
            " /* GoogleService-Info.plist */; };", 1)
        p = p.replace("/* Begin PBXFileReference section */",
            "/* Begin PBXFileReference section */\n\t\t" + fid +
            " /* GoogleService-Info.plist */ = {isa = PBXFileReference; lastKnownFileType = text.plist.xml;"
            " path = \"GoogleService-Info.plist\"; sourceTree = \"<group>\"; };", 1)
        # into the App group, beside Info.plist, and into the Resources phase
        p = re.sub(r"(/\* Info.plist \*/,\n)", r"\1\t\t\t\t" + fid + " /* GoogleService-Info.plist */,\n", p, count=1)
        p = re.sub(r"(isa = PBXResourcesBuildPhase;\n\t\t\tbuildActionMask = \d+;\n\t\t\tfiles = \(\n)",
                   r"\1\t\t\t\t" + bid + " /* GoogleService-Info.plist in Resources */,\n", p, count=1)
    pbx.write_text(p)
    print("  project.pbxproj: entitlements and the Firebase plist in the target")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--android", action="store_true")
    ap.add_argument("--ios", action="store_true")
    ap.add_argument("--aps", default="production", choices=["development", "production"],
                    help="production for TestFlight and the App Store, development for a debug build")
    a = ap.parse_args()
    if not (a.android or a.ios):
        ap.error("say --android, --ios or both")
    if a.android: android()
    if a.ios: ios(a.aps)
